### PR TITLE
Functions and constructors to auto-convert between Int and Float

### LINKED ISSUE #280: When an integer is passed to a method on a float parameter it should be converted to float.
Currently the interpreter is raising an exception if you send an integer number to a method that expects a float. 
Roku does convert that number to float transparently.

### PR DESCRIPTION
**Pull request by lvcabral**
Roku does truncate float to integer (not round) so I also changed the constructor of Int32 and Int64 to correctly mimic the behavior.

fixes #280

### CODE REVIEW

File: src/brsTypes/Callable.ts [hunk 1]
```diff
@@ -255,6 +257,24 @@ export class Callable implements Brs.BrsValue {
                 return;
             }
 
+            if (
+                expected.type.kind === Brs.ValueKind.Float &&
+                received.kind === Brs.ValueKind.Int32
+            ) {
+                let old = args[index] as Int32;
```
Comment (sjbarag) [inline src/brsTypes/Callable.ts]: Consider using the `received` variable in place of this new `old` one — the TypeScript compiler already knows it's an Int32 because of the `ValueKind` comparison on line 262, so there's no need to re-cast it here!

File: test/brsTypes/Int64.test.js [hunk 2]
```diff
@@ -11,18 +11,18 @@ const {
 const Long = require("long");
 
 describe("Int64", () => {
-    it("rounds initial values to integers", () => {
+    it("truncates initial values to integers", () => {
         let three = new Int64(3.4);
         let four = new Int64(3.5);
```
Comment (sjbarag) [inline test/brsTypes/Int64.test.js]: Would you mind renaming the variable `four` to `threePointFive` or something?   Or drop the intermediate values entirely, since both `3.4` and `3.5` should convert to `3` either way!  The meaning of the variable names is no longer useful, since they have the same resulting value 😄

**Comment by lvcabral** [comment]
Updated with suggestion changes
