### PR TITLE
Fixes many sorting issues with mixed arrays (fixes #591)

### LINKED ISSUE #591: Sorting Array of numbers actually sorts in alphabetical order, instead of by value
ifArray.Sort() method does not properly sort an array of integers. Instead of sorting in ascending value, instead it sorts the values as if they were strings, so 10 comes before 9, etc.

In the BRS command line:
```
brs> a = [3, 2, 1, 11]
brs> a.sort()
brs> ?a
<Component: roArray> =
[
    1
    11
    2
    3
]
brs>
```

But running on an actual Roku:
```
Brightscript Debugger> 
a = [3, 2, 1, 11]

Brightscript Debugger> 
a.sort()

Brightscript Debugger> 
?a
<Component: roArray> =
[
    1
    2
    3
    11
]

Brightscript Debugger> 
```

### PR DESCRIPTION
**Pull request by markwpearce**
Refactors roArray sort() and sortBy() so it more closely matches what Roku actually does.

Fixes #591

**array.sort()** example: 

```
Brightscript Debugger> 
arr=["a", 1, ["sub", "array"], 9, 10, "B", {obj: "foo"}, {obj: "bar"}, false, "c", true, false]

Brightscript Debugger> 
arr.sort()

Brightscript Debugger> 
?arr
<Component: roArray> =
[
    1
    9
    10
    "B"
    "a"
    "c"
    <Component: roAssociativeArray>
    <Component: roAssociativeArray>
    <Component: roArray>
    false
    true
    false
]

Brightscript Debugger> 
?arr[6]
<Component: roAssociativeArray> =
{
    obj: "foo"
}

Brightscript Debugger> 
?arr[7]
<Component: roAssociativeArray> =
{
    obj: "bar"
}

Brightscript Debugger> 
```

**Mixed Arrays seem to get sorted in this order (tested with Roku OS 9.4):
1. numbers in numeric order
2. strings in alphabetical order,
3. assocArrays in original order
4. everything else in original order**

.... 

here's another example:

```
Brightscript Debugger> 
arr = [{bar:"def"}, {bar:"abc"},{foo: "bar"}, {foo:"abc"},3,2,1,"def", "abc", false, true, false, ["sub","array"], {foo: "buz"}, false]

Brightscript Debugger> 
arr.sort():?arr

<Component: roArray> =
[
    1
    2
    3
    "abc"
    "def"
    <Component: roAssociativeArray>
    <Component: roAssociativeArray>
    <Component: roAssociativeArray>
    <Component: roAssociativeArray>
    <Component: roAssociativeArray>
    false
    true
    false
    <Component: roArray>
    false
]

Brightscript Debugger> 
?arr[5];arr[6]arr[7];arr[8]
<Component: roAssociativeArray> =
{
    bar: "def"
}<Component: roAssociativeArray> =
{
    bar: "abc"
}<Component: roAssociativeArray> =
{
    foo: "bar"
}<Component: roAssociativeArray> =
{
    foo: "abc"
}
```

**SortBy is a little different**

it goes : 

1. numbers in numeric order
2. strings in alphabetical order,
3. assocArrays
   1. any assoc array with the key, sorted by the value with that key
   2. any other assocArray, in original order 
4. everything else in original order

Here's a sortBy() example ---

```
Brightscript Debugger> 
arr = [{bar:"def"}, {bar:"abc"},{foo: "bar"}, {foo:"abc"},3,2,1,"def", "abc", false, true, false, ["sub","array"], {foo: "buz"}, false]

Brightscript Debugger> 
arr.sortBy("foo"):?arr
<Component: roArray> =
[
    3
    2
    1
    "def"
    "abc"
    <Component: roAssociativeArray>
    <Component: roAssociativeArray>
    <Component: roAssociativeArray>
    <Component: roAssociativeArray>
    <Component: roAssociativeArray>
    false
    true
    false
    <Component: roArray>
    false
]

Brightscript Debugger>
?arr[5];arr[6]arr[7];arr[8];arr[9]
<Component: roAssociativeArray> =
{
    foo: "abc"
}<Component: roAssociativeArray> =
{
    foo: "bar"
}<Component: roAssociativeArray> =
{
    foo: "buz"
}<Component: roAssociativeArray> =
{
    bar: "def"
}<Component: roAssociativeArray> =
{
    bar: "abc"
}

```

### CODE REVIEW

File: src/brsTypes/components/RoArray.ts [hunk 1]
```diff
@@ -1,11 +1,42 @@
...
+            let bStr = b.toString();
+            if (caseInsensitive) {
+                aStr = aStr.toLowerCase();
+                bStr = bStr.toLowerCase();
+            }
+            // roku does not use locale for sorting strings
+            compare = aStr > bStr ? 1 : -1;
+        } else if (isBrsNumber(a) && isBrsNumber(b)) {
+            compare = (a as Comparable).greaterThan(b).toBoolean() ? 1 : -1;
+        } else if (isBrsBoolean(a) && isBrsBoolean(b)) {
```
Comment (strattonbrazil) [inline src/brsTypes/components/RoArray.ts:31]: Does this match the Roku implementation?

File: src/brsTypes/components/RoArray.ts [hunk 2]
```diff
@@ -1,11 +1,42 @@
...
+            compare = 0;
+        } else {
+            compare = a > b ? 1 : -1;
```
Comment (strattonbrazil) [inline src/brsTypes/components/RoArray.ts:34]: If we get to this point we should raise a TypeMismatch exception to match the Roku implementation. 

```
x = 3
y = "7"
if x < y (raises type mismatch error)
```

File: src/brsTypes/components/RoArray.ts [hunk 3]
```diff
@@ -214,41 +245,13 @@ export class RoArray extends BrsComponent implements BrsValue, BrsIterable {
             if (flags.toString().match(/([^ir])/g) != null) {
                 interpreter.stderr.write("roArray.Sort: Flags contains invalid option(s).\n");
             } else {
+                const caseInsensitive = flags.toString().indexOf("i") > -1;
```
Comment (strattonbrazil) [inline src/brsTypes/components/RoArray.ts:248]: Much more legible!

File: src/brsTypes/components/RoArray.ts [hunk 4]
```diff
@@ -214,41 +245,13 @@ export class RoArray extends BrsComponent implements BrsValue, BrsIterable {
...
-                        }
-                    }
-                    if (flags.toString().indexOf("r") > -1) {
-                        compare = -compare;
-                    }
-                    return compare;
+                    return sortCompare(a, b, caseInsensitive);
                 });
+                if (flags.toString().indexOf("r") > -1) {
+                    this.elements = this.elements.reverse();
```
Comment (strattonbrazil) [inline src/brsTypes/components/RoArray.ts:253]: Also more readable. Thanks.

**Review by strattonbrazil — COMMENTED** [review]
Thanks for the fix. One note on matching the Roku implementation.

**Review by lkipke — APPROVED** [review]
Assuming this all matches RBI behavior, this looks good to me, thanks for making it more readable 👍

File: src/brsTypes/components/RoArray.ts (hunk 1 above)
Comment (markwpearce) [reply src/brsTypes/components/RoArray.ts:31]: This doesn't actually,... Working on a fix now

**Comment by markwpearce** [comment]
I updated this PR after doing some more testing. I think my updates are actually much more readable, too.

File: src/brsTypes/components/RoArray.ts (hunk 2 above)
Comment (markwpearce) [reply src/brsTypes/components/RoArray.ts]: This is no longer an issue. I discovered all other types get sorted in original order.

File: src/brsTypes/components/RoArray.ts (hunk 1 above)
Comment (markwpearce) [reply src/brsTypes/components/RoArray.ts]: fixed in latest commit

File: src/brsTypes/components/RoArray.ts [hunk 5]
```diff
@@ -266,48 +310,31 @@ export class RoArray extends BrsComponent implements BrsValue, BrsIterable {
...
+                const originalArrayCopy = [...this.elements];
+                this.elements = this.elements.sort((a, b) => {
                     var compare = 0;
                     if (a instanceof RoAssociativeArray && b instanceof RoAssociativeArray) {
-                        if (
-                            a.elements.has(fieldName.toString().toLowerCase()) &&
-                            b.elements.has(fieldName.toString().toLowerCase())
-                        ) {
+                        let aHasField = a.elements.has(fieldName.toString().toLowerCase()),
+                            bHasField = b.elements.has(fieldName.toString().toLowerCase());
```
Comment (sjbarag) [inline src/brsTypes/components/RoArray.ts:319]: I don't think there's a lint rule around this (I'm sorry!) but local convention is to use separate `let` or `const` keywords for each declaration, like you did on lines 313 and 314.  Would you mind adjusting these?

```suggestion
                        let aHasField = a.elements.has(fieldName.toString().toLowerCase());
                        let bHasField = b.elements.has(fieldName.toString().toLowerCase());
```

File: test/brsTypes/components/RoArray.test.js [hunk 6]
```diff
@@ -663,6 +728,54 @@ describe("RoArray", () => {
                 expect(src.elements).toEqual([i2, i1, a, b, a1, a2, a3, ar]);
             });
 
+            it("sorts the array based on AA valid mixed field", () => {
+                let a3 = new RoAssociativeArray([
+                    { name: new BrsString("id"), value: new Int32(3) },
+                    { name: new BrsString("name"), value: new BrsString("Betty") },
+                    { name: new BrsString("data"), value: new BrsString("abc") },
+                ]);
```
Comment (sjbarag) [inline test/brsTypes/components/RoArray.test.js:736]: I was a little surprised to see `a3` declared before `a1` and `a2` — is there any particular reason for that?

**Review by sjbarag — APPROVED** [review]
Oh wow, great catch @markwpearce !  Thanks for the PR — this must have taken a lot of iteration, and I really appreciate it 😃 

I've got two very small requests (all style related), but I'd be happy to merge this in as soon as those are resolved.  Nice work!

**Review by sjbarag — CHANGES_REQUESTED** [review]
Bah this is embarrassing, I meant to click "request changes" to make the next steps clear — I'm sorry!

**Comment by markwpearce** [comment]
@sjbarag - Updated with some fixes you requested.


Any chance you might also review https://github.com/sjbarag/brs/pull/583 ?

File: test/brsTypes/components/RoArray.test.js [hunk 7]
```diff
@@ -338,30 +338,30 @@ describe("RoArray", () => {
...
+                    i2, // value = 2
+                    f2_5, // value = 2.5
+                    i3, // value = 3
+                    i10, // value = 10
+                    strA, // strings in order - value = "a"
+                    strAaa, // value = "aaa"
+                    strB, // value = "b"
+                    strBaa, //value = "baa"
+                    strC, // value = "c"
+                    aa1, // assoc arrays in original order
```
Comment (sjbarag) [inline test/brsTypes/components/RoArray.test.js:362]: These comments are extremely helpful — thank you!

**Review by sjbarag — APPROVED** [review]
Excellent work, @markwpearce.  Thanks for the updates!
